# Project
[project]
name = "NBStorage"
version = "0.0.1"
requires-python = ">=3.13"
authors = [
    {name = "Бобошко Антон", email = "anton.bobbis@gmail.com"}
]
maintainers = [
    {name = "Бобошко Антон", email = "anton.bobbis@gmail.com"}
]
description = "Менеджер паролей"
readme = "README.md"
license = {file = "LICENSE"}
keywords = [
    "NBStorage",
    "nb",
    "notibit",
    "storage",
    "manager",
    "password"
]
classifiers = [
  "Development Status :: 1 - Planning",
  "Intended Audience :: Regular Users",
  "Programming Language :: Python :: 3.13",
  "Operating System :: Windows 10"
]

[project.urls]
Homepage = "https://github.com/Notikay/NBStorage"
Documentation = "https://github.com/Notikay/NBStorage/tree/master/docs/"
Repository = "https://github.com/Notikay/NBStorage.git"
"Bug Tracker" = "https://github.com/Notikay/NBStorage/issues"
Changelog = "https://github.com/Notikay/NBStorage/tree/master/CHANGELOG.md"

# Ruff
[tool.ruff]
required-version = ">=0.14.13"
exclude = [
    "__pycache__",
    ".venv",
    ".git",
    "build",
    "dist",
    "data",
    "docs",
    "logs",
    ".ruff_cache",
    ".mypy_cache",
    ".pytest_cache",
]
line-length = 79
target-version = "py313"

[tool.ruff.lint.pycodestyle]
max-doc-length = 72

[tool.ruff.lint.per-file-ignores]
"*.ipynb" = [
    "E402",  # Импорты могут быть не в начале
    "T201"  # Разрешение print() в отчетах
]
"tests/*" = [
    "S101"  # Разрешение assert в тестах
]

[tool.ruff.format]
docstring-code-format = true

# MyPy
[tool.mypy]
python_version = "3.13"
mypy_path = ["src"]

# Pytest
[tool.pytest.ini_options]
testpaths = ["tests"]